import { useBand } from "@/context/BandContext";

export default function AlertHistory() {
  const { currentBand } = useBand();

  if (!currentBand) {
    return <p className="p-6">No band selected.</p>;
  }

  const alerts = currentBand.alerts || [];

  return (
    <div className="min-h-screen bg-gray-100 p-6">
      <h2 className="text-2xl font-bold mb-1">
        Alert History – {currentBand.name}
      </h2>
      <p className="text-sm text-gray-600 mb-6">
        All emergency and health alerts generated by this band
      </p>

      {alerts.length === 0 ? (
        <div className="bg-white p-6 rounded-xl shadow text-gray-500">
          No alerts recorded yet.
        </div>
      ) : (
        <div className="space-y-4">
          {alerts.map((alert, index) => (
            <div
              key={index}
              className="bg-white p-4 rounded-xl shadow flex justify-between items-center"
            >
              <div>
                <p className="font-semibold">{alert.type}</p>
                <p className="text-sm text-gray-600">{alert.message}</p>
              </div>

              <div className="text-xs text-gray-500">
                {new Date(alert.time).toLocaleString()}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
